stages:
  - build
  - docs
  - deploy

include:
  - local: '.gitlab/ci/build.yml'

variables:
  PY_VERSION: "3.11"
  DOCS_SRC: "docs/source"
  BUILD_DIR: "docs/build/html"

docs:
  image: python:${PY_VERSION}
  stage: docs
  before_script:
    - python -m pip install uv
    - uv sync --group docs --no-install-project
  script:
    - uv run sphinx-build -b html "$DOCS_SRC" "$BUILD_DIR"
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

pages:
  stage: deploy
  image: python:${PY_VERSION}
  dependencies:
    - docs
  script:
    - mkdir -p public
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - main
    - dev
